// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aglcom.proto
#ifndef GRPC_aglcom_2eproto__INCLUDED
#define GRPC_aglcom_2eproto__INCLUDED

#include "aglcom.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace aglcom {

class DemoMessage final {
 public:
  static constexpr char const* service_full_name() {
    return "aglcom.DemoMessage";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::aglcom::DemoReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>> AsyncSendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>>(AsyncSendDemoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>> PrepareAsyncSendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>>(PrepareAsyncSendDemoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>* AsyncSendDemoRaw(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::aglcom::DemoReply>* PrepareAsyncSendDemoRaw(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::aglcom::DemoReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>> AsyncSendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>>(AsyncSendDemoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>> PrepareAsyncSendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>>(PrepareAsyncSendDemoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response, std::function<void(::grpc::Status)>) override;
      void SendDemo(::grpc::ClientContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>* AsyncSendDemoRaw(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::aglcom::DemoReply>* PrepareAsyncSendDemoRaw(::grpc::ClientContext* context, const ::aglcom::DemoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendDemo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendDemo(::grpc::ServerContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendDemo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendDemo(::grpc::ServerContext* context, ::aglcom::DemoRequest* request, ::grpc::ServerAsyncResponseWriter< ::aglcom::DemoReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendDemo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendDemo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::aglcom::DemoRequest, ::aglcom::DemoReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::aglcom::DemoRequest* request, ::aglcom::DemoReply* response) { return this->SendDemo(context, request, response); }));}
    void SetMessageAllocatorFor_SendDemo(
        ::grpc::MessageAllocator< ::aglcom::DemoRequest, ::aglcom::DemoReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::aglcom::DemoRequest, ::aglcom::DemoReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendDemo(
      ::grpc::CallbackServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendDemo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendDemo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendDemo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendDemo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendDemo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendDemo(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendDemo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendDemo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendDemo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::aglcom::DemoRequest, ::aglcom::DemoReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::aglcom::DemoRequest, ::aglcom::DemoReply>* streamer) {
                       return this->StreamedSendDemo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendDemo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendDemo(::grpc::ServerContext* /*context*/, const ::aglcom::DemoRequest* /*request*/, ::aglcom::DemoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendDemo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::aglcom::DemoRequest,::aglcom::DemoReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendDemo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendDemo<Service > StreamedService;
};

}  // namespace aglcom


#endif  // GRPC_aglcom_2eproto__INCLUDED
